# ANN constants
INPUT_LAYER_SIZE = 21
OUTPUT_LAYER_SIZE = 1
INPUT_LAYER_WEIGHTS = [1] * INPUT_LAYER_SIZE
INIT_WEIGHTS = [0] * INPUT_LAYER_SIZE
BIAS = True

# Data constants
TRAIN_SET_SIZE = 1000
TEST_SET_SIZE = 1000
TRAIN_SET_FILE_NAME = "train_set.txt"
TEST_SET_FILE_NAME = "test_set.txt"
